services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true

    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST:-true}
      AUTH_SECRET: ${AUTH_SECRET}
      HOSTNAME: ${WEB_HOSTNAME}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    networks:
      - trilhos
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=3 --spider http://0.0.0.0:3000" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
    restart: "no"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    command: [ "npx", "drizzle-kit", "migrate" ]
    depends_on:
      database:
        condition: service_healthy
    networks:
      - trilhos

  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - trilhos
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${DB_USER} -d ${DB_NAME}'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  pgdata:


networks:
  trilhos:
